### ISSUE TITLE
Convert Author Names to Links

### ISSUE THREAD

**Issue by gupta-ji6** [scriptified/scriptified#70]
We have saved author websites/portfolios in our [scriptified-cms](https://github.com/scriptified/scriptified-cms). We will need to add those links in author names from our API. Easy!

### Tasks

- [ ] Add tip source in Tip Of The Week
- [ ] Add hyperlinks in author name in Articles
- [ ] Add hyperlinks in author name in Tools
- [ ] Add author name in Tech Talks
- [ ] Add Quiz source
- [ ] Add GIF source

**Comment by contracamilo** [comment]
Hey @gupta-ji6  I can work on this issue :) .

**Comment by gupta-ji6** [comment]
sure @contracamilo, go ahead! I've assigned it to you :)

mention @scriptified/core-team if you need help with understanding the requirements or anything else 🙌🏻
